services:
  py:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./project/content:/project/content
      - ./project/output:/project/output
      - ./project/Makefile:/project/Makefile
      - ./project/pelicanconf.py:/project/pelicanconf.py
