services:
  py:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    volumes:
      # - ./project:/project
      # - pelican-project:/project
      - ./project/content:/project/content
      - ./project/output:/project/output
      - ./project/pelicanconf.py:/project/pelicanconf.py

# volumes:
  # pelican-project:
